### ISSUE TITLE
What is NuVISION ???

### ISSUE THREAD

**Issue by Anirudh-Pranesh** [PushkarP-404/NuVISION#1]
Is this your CS project ? or is it some company u started on your own  ?

**Comment by PushkarP-404** [comment]
cs project
i found making an organisation on github better so that i can easily manage
all the repos

i realised after a while, i made a organization with the same name so i thought you were walking about that
didnt know you saw the webpage

**Comment by PushkarP-404** [comment]
bro how do you know about it ??
my organization is private on github

**Comment by Anirudh-Pranesh** [comment]
isnt just one repo enough for one project lol ?

**Comment by PushkarP-404** [comment]
i just make a new for every new feature i add, didnt know how to use pull and stuff

and also we have different programs right like predictions and dashboard are going to be separate

**Comment by Anirudh-Pranesh** [comment]
bro is rlly making a whole new repo for new updates 💀
